// Generated by CoffeeScript 1.4.0
var Entries, Entry, EntryView, EntrylistView, Finder, MorePageView, NavigatorView;

Entry = Backbone.Model.extend({});

Entries = Backbone.Collection.extend({
  model: Entry,
  initialize: function() {
    return _.bindAll(this, 'setUrl');
  },
  /*
    Entryisのurlを設定します
    このメソッドを使えばメソッドチェーンでfetchなどが可能です
  */

  setUrl: function(url) {
    this.url = url;
    return this;
  }
});

Finder = Backbone.Model.extend({
  defaults: {
    pageNumber: 1,
    pageSize: 5,
    prevQuery: {},
    predicate: function(query, entry) {
      var key, val;
      for (key in query) {
        val = query[key];
        if (val !== entry.get(key)) {
          return false;
        }
      }
      return true;
    }
  },
  initialize: function() {
    /*
        イベントの設定
    */

    var filtering, filteringOne, initializePage,
      _this = this;
    filtering = _.bind(this.filtering, this, null, null);
    filteringOne = function(model) {
      return _this.filteringOne(model);
    };
    initializePage = _.bind(this.toPage, this, 1);
    _.bindAll(this, 'load', 'filteringOne', 'filtering', 'hasNextPage', 'hasPrevPage', 'nextPage', 'prevPage', 'morePage', 'toPage', 'pageSizeIsInfinity', 'getMaxPageNumber', 'getPageEntries', '_onCollectionEvent', '_pageAdd');
    if (!this.has('allEntries')) {
      this.set('allEntries', new Entries);
    }
    if (!this.has('filteredEntries')) {
      this.set('filteredEntries', new Entries);
    }
    if (!this.has('selectedEntries')) {
      this.set('selectedEntries', new Entries);
    }
    this.get('allEntries').on("reset", filtering);
    this.get('allEntries').on("add", filteringOne);
    this.get('filteredEntries').on("add", this._pageAdd);
    this.get('filteredEntries').on("reset", initializePage);
    this.get('selectedEntries').on('all', this._onCollectionEvent);
    this.on("change:pageSize", initializePage);
    return this.on("change:pageNumber", function() {
      return _this.trigger("change:page");
    });
  },
  /*
    エントリーデータを読み込みます
    引数
      1.URLもしくはエントリーデータの配列
      2.オプション
  */

  load: function(url, options) {
    var _this = this;
    if (url == null) {
      url = this.get('url');
    }
    if (options == null) {
      options = {};
    }
    if (_.isString(url)) {
      return this.get('allEntries').setUrl(url).fetch(options).then(function() {
        return _this.toPage(1);
      });
    } else if (_.isArray(url || _.isObject(url))) {
      this.get('allEntries').reset(url, options);
      return this.toPage(1);
    } else {
      throw new Error("Can not load. Invalid argument.");
    }
  },
  /*
    モデル1つに対して述語が真ならばfilterdEntriesに追加します
  */

  filteringOne: function(query, model, predi) {
    var filtered;
    if (query == null) {
      query = this.get('prevQuery');
    }
    if (predi == null) {
      predi = this.get('predicate');
    }
    if (!(model != null)) {
      model = query;
      query = this.get('prevQuery');
    }
    this.set('prevQuery', query);
    predi = _.bind(predi, this, query);
    filtered = this.get('filteredEntries');
    if (predi(model && !filtered.include(model))) {
      filtered.add(model);
    }
    return this;
  },
  /*
    allEntriesに対して検索します
    引数
      1.検索条件
      2.述語関数
  */

  filtering: function(query, predi) {
    if (query == null) {
      query = this.get('prevQuery');
    }
    if (predi == null) {
      predi = this.get('predicate');
    }
    predi = _.bind(predi, this, query);
    this.set('prevQuery', query);
    this.get('filteredEntries').reset(this.get('allEntries').filter(predi));
    return this;
  },
  /*
    次のページがあるなら真、そうでなければ偽を返す
  */

  hasNextPage: function() {
    return this.get('pageNumber') < this.getMaxPageNumber();
  },
  /*
    前のページがあるなら真、そうでなければ偽を返す
  */

  hasPrevPage: function() {
    return 1 < this.get('pageNumber');
  },
  /*
    次のページへ移動する
  */

  nextPage: function() {
    if (!this.hasNextPage()) {
      return this;
    }
    return this.toPage(this.get('pageNumber') + 1);
  },
  /*
    前のページへ移動する
  */

  prevPage: function() {
    if (!this.hasPrevPage()) {
      return this;
    }
    return this.toPage(this.get('pageNumber') - 1);
  },
  /*
    現在のページに次のページのEntryを追加します
  */

  morePage: function() {
    var page;
    if (!this.hasNextPage()) {
      return this;
    }
    page = this.get('pageNumber') + 1;
    this.get('selectedEntries').add(this.getPageEntries(page));
    return this.set('pageNumber', page);
  },
  /*
    指定したページへ移動します
  */

  toPage: function(page) {
    if (_.isString(page)) {
      page = parseInt(pase);
    }
    this.get('selectedEntries').reset(this.getPageEntries(page));
    this.set('pageNumber', 0, {
      silent: true
    });
    return this.set('pageNumber', page);
  },
  /*
    ページサイズが無限個になっているならば真、そうでなければ偽を返す
    ページサイズを無限個に設定するには0以下の値を設定してください。
  */

  pageSizeIsInfinity: function(pageSize) {
    if (pageSize == null) {
      pageSize = this.get('pageSize');
    }
    return !(pageSize != null) || pageSize <= 0;
  },
  /*
    最大のページ番号を返します
  */

  getMaxPageNumber: function() {
    var allSize;
    if (this.pageSizeIsInfinity()) {
      return 1;
    }
    allSize = this.get('filteredEntries').length;
    return Math.ceil(allSize / this.get('pageSize'));
  },
  /*
    指定したページ番号のEntryの配列を返します
  */

  getPageEntries: function(page) {
    var pageSize, skipSize;
    pageSize = this.get('pageSize');
    if (this.pageSizeIsInfinity(pageSize)) {
      return this.get('filteredEntries').chain().value();
    }
    skipSize = (page - 1) * pageSize;
    return this.get('filteredEntries').chain().tail(skipSize).head(pageSize).value();
  },
  /*
    現在のページにEntryを追加します
  */

  _pageAdd: function(model, collection) {
    var selected;
    selected = this.get('selectedEntries');
    if (selected.length < this.get("pageSize")) {
      return selected.add(model);
    }
  },
  /*
    受け取ったイベントを、自分のイベントとして吐き出します
  */

  _onCollectionEvent: function(event, model, collection, options) {
    if (event === "add") {
      this.trigger('selected', model, collection, options);
    }
    if (event === "remove") {
      this.trigger('unselected', model, collection, options);
    }
    return this.trigger.apply(this, arguments);
  }
});

EntryView = Backbone.View.extend({
  options: {
    template: "#entry-view-tmpl"
  },
  initialize: function() {
    _.bindAll(this, 'render', '_getTemplate');
    if (this.options.events != null) {
      this.events = this.options.events;
    }
    return this.template = this._getTemplate(this.options.template);
  },
  render: function() {
    this.$el.html(this.template(this.model.toJSON()));
    return this;
  },
  /*
    テンプレートを取得します
    メモ化していますので、引数が同じ関数を複数回呼ぶ場合、2回目以降はキャッシュされたものが返ります
  */

  _getTemplate: _.memoize(function(tmpl) {
    tmpl = $(tmpl);
    if (tmpl.length === 0) {
      throw new Error("A template does not exist");
    }
    return _.template(tmpl.html());
  })
});

EntrylistView = Backbone.View.extend({
  options: {
    'EntryView': EntryView,
    onAdd: function(view) {
      return view.$el.stop().css('opacity', 1.0).hide().fadeIn();
    },
    entryOptions: {}
  },
  initialize: function() {
    _.bindAll(this, "render", "_add", "_getView");
    this.model.on("reset", this.render);
    return this.model.on("add", this._add);
  },
  render: function() {
    this.$el.html('');
    this.model.get('selectedEntries').each(this._add);
    return this;
  },
  _add: function(entry) {
    var view;
    view = this._getView(entry);
    this.$el.append(view.render().el);
    if (_.isFunction(this.options.onAdd)) {
      return this.options.onAdd(view);
    }
  },
  _getView: _.memoize(function(model) {
    var options;
    options = _.extend({}, {
      model: model
    }, this.options.entryOptions);
    return new this.options.EntryView(options);
  }, function(model) {
    return model.id;
  })
});

NavigatorView = Backbone.View.extend({
  options: {
    viewCount: 5,
    separater: ' | ',
    nextString: '次のページ',
    prevString: '前のページ',
    exString: '...'
  },
  events: {
    "click a.nextlink": '_nextPage',
    "click a.prevlink": '_prevPage',
    "click a.page-jump": '_toPage'
  },
  initialize: function() {
    _.bindAll(this, 'render', '_nextPage', '_prevPage', '_toPage');
    return this.model.on("change:page", this.render);
  },
  render: function() {
    var i, maxPage, nowPage, op, _i;
    op = this.options;
    nowPage = this.model.get('pageNumber');
    maxPage = this.model.getMaxPageNumber();
    this.$el.html('');
    if (maxPage <= 1) {
      this.$el.hide();
    } else {
      this.$el.show();
      if (this.model.hasPrevPage()) {
        this.$el.append("<a class='prevlink' href='#prev'>" + op.prevString + "</a><span>" + op.separater + "</span>");
      }
      if (1 < nowPage - op.viewCount) {
        this.$el.append("<span>" + op.exString + "</span>");
      }
      for (i = _i = 1; 1 <= maxPage ? _i <= maxPage : _i >= maxPage; i = 1 <= maxPage ? ++_i : --_i) {
        if ((nowPage - op.viewCount <= i && i <= nowPage + op.viewCount)) {
          if (i === nowPage) {
            this.$el.append("<span>" + i + "</span>");
          } else {
            this.$el.append("<a class='page-jump' href='#" + i + "page' data-to-page='" + i + "'>" + i + "</a>");
          }
        }
      }
      if (nowPage + op.viewCount < maxPage) {
        this.$el.append("<span>" + op.exString + "</span>");
      }
      if (this.model.hasNextPage()) {
        this.$el.append(" " + op.separater + " <a class='nextlink' href='#next'>" + op.nextString + "</a>");
      }
    }
    return this;
  },
  _nextPage: function(event) {
    this.model.nextPage();
    return false;
  },
  _prevPage: function(event) {
    this.model.prevPage();
    return false;
  },
  _toPage: function(event) {
    this.model.toPage($(event.currentTarget).data('to-page'));
    return false;
  }
});

MorePageView = Backbone.View.extend({
  events: {
    "click": '_morePage'
  },
  initialize: function() {
    _.bindAll(this, 'render', '_morePage');
    this.model.on("change:page", this.render);
    return this.render();
  },
  render: function() {
    if (this.model.get('pageNumber') < this.model.getMaxPageNumber()) {
      this.$el.show();
    } else {
      this.$el.hide();
    }
    return this;
  },
  _morePage: function(event) {
    this.model.morePage();
    return false;
  }
});

/*
using = ->
  classes = ['Entry','Entries','Finder','EntryView','EntrylistView','NavigatorView','MorePageView']
  this[name] = root[name] for name in classes
*/

